### ISSUE TITLE
Multi-tenant

### ISSUE THREAD

**Issue by tjementum** [platformplatform/PlatformPlatform#116]
```[tasklist]
### Tasks
- [ ] https://github.com/platformplatform/PlatformPlatform/issues/581
- [ ] https://github.com/platformplatform/PlatformPlatform/issues/582
- [ ] https://github.com/platformplatform/PlatformPlatform/issues/583
- [ ] https://github.com/platformplatform/PlatformPlatform/issues/584
```

See https://learn.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-di%2Cexpression-api-with-constant#managing-state-in-pooled-contexts
