### ISSUE TITLE
Design system

### ISSUE THREAD

**Issue by raix** [PlatformPlatform/platformplatform#208]
```[tasklist]
### Tasks
- [ ] Create styled component library based on RAC
- [ ] [Dynamic OKLCH themes in Tailwind](https://evilmartians.com/chronicles/better-dynamic-themes-in-tailwind-with-oklch-color-magic)
- [ ] Enable Theme mode (light/dark/system)
- [ ] Charts & Diagrams
- [ ] Set up Figma file?
- [ ] Set up Storybook ?
```
