### ISSUE TITLE
.NET 8 upgrade

### ISSUE THREAD

**Issue by tjementum** [platformplatform/PlatformPlatform#246]
```[tasklist]
### Tasks
- [ ] https://github.com/PlatformPlatform/platformplatform/issues/215
- [ ] https://github.com/PlatformPlatform/platformplatform/issues/216
- [ ] https://github.com/PlatformPlatform/platformplatform/issues/235
- [ ] https://github.com/PlatformPlatform/platformplatform/issues/221
- [ ] https://github.com/PlatformPlatform/platformplatform/issues/223
```
