### ISSUE TITLE
Developer CLI

### ISSUE THREAD

**Issue by tjementum** [platformplatform/PlatformPlatform#249]
```[tasklist]
### Tasks
- [ ] https://github.com/platformplatform/PlatformPlatform/issues/223
- [ ] https://github.com/platformplatform/PlatformPlatform/issues/250
- [ ] https://github.com/platformplatform/PlatformPlatform/issues/264
- [ ] https://github.com/platformplatform/PlatformPlatform/issues/267
- [ ] https://github.com/platformplatform/PlatformPlatform/issues/296
```
