### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by tjementum** [platformplatform/PlatformPlatform#254]
https://lingui.dev
https://blog.nimblepros.com/blogs/localization-aspnet-core-api
https://crowdin.com
```[tasklist]
### Tasks
- [ ] https://github.com/platformplatform/PlatformPlatform/pull/259
- [ ] https://github.com/platformplatform/PlatformPlatform/issues/260
- [ ] https://github.com/platformplatform/PlatformPlatform/pull/253
- [ ] https://github.com/platformplatform/PlatformPlatform/issues/258
```

**Comment by raix** [comment]
`OrchardCore.Localization.PortableObject`
`dotnet tool install --global OrchardCoreContrib.PoExtractor`
https://docs.orchardcore.net/en/main/docs/reference/modules/Localize/
