### ISSUE TITLE
Tracking and logging

### ISSUE THREAD

**Issue by tjementum** [PlatformPlatform/platformplatform#26]

**Comment by tjementum** [comment]
- [ ] Set up Application Insights using Managed Identity
- [ ] Add generic telemetric to foundation
- [ ] Set up Serilog for logging
- [ ] Set up continuous export to data platfrom
- [ ] Mask all PII data in telemetric entries
- [ ] Manage user sessions (for Application Insights and Amplitude)
- [ ] Manage correlation IDs between systems
- [ ] Proxy front-end tracking through back-end
- [ ] Add tracking to worker roles
