### ISSUE TITLE
Tracking and logging

### ISSUE THREAD

**Issue by tjementum** [platformplatform/PlatformPlatform#27]
```[tasklist]
### Tasks
- [ ] https://github.com/platformplatform/PlatformPlatform/issues/240
- [ ] https://github.com/platformplatform/PlatformPlatform/issues/244
- [ ] https://github.com/platformplatform/PlatformPlatform/issues/241
- [ ] https://github.com/platformplatform/PlatformPlatform/issues/274
- [ ] https://github.com/platformplatform/PlatformPlatform/issues/266
- [ ] https://github.com/platformplatform/PlatformPlatform/issues/281
- [ ] https://github.com/platformplatform/PlatformPlatform/issues/279
- [ ] https://github.com/platformplatform/PlatformPlatform/issues/275
- [ ] https://github.com/platformplatform/PlatformPlatform/issues/283
```

https://www.treblle.com/features/api-analytics
https://youtu.be/c4AJlZeX2fE?si=kND5nK3uoo74JU-z
