### ISSUE TITLE
Frontend foundation

### ISSUE THREAD

**Issue by tjementum** [PlatformPlatform/platformplatform#36]
```[tasklist]
### Tasks
- [ ] https://github.com/PlatformPlatform/platformplatform/issues/189
- [ ] https://github.com/PlatformPlatform/platformplatform/issues/194
- [ ] https://github.com/PlatformPlatform/platformplatform/issues/203
```

https://component.gallery/design-systems/

## Front end foundation
- Libraries that can make you write code fast. Head less.
- Adobe React Aria (https://react-spectrum.adobe.com/react-aria/). React hooks, you can write your own styles

## Customizable Components - Customizable Foundation  More than foundation, some custom stiles 
- Tailwind
- Chakra UI - https://chakra-ui.com/
- FastDesign - https://www.fast.design/
- NextUI - https://nextui.org/
- Reshaped - https://reshaped.so/

## Design Systems
These are full frameworks. Recognizable like Bootstrap.
- Material UI
- Ant Design
- https://react-spectrum.adobe.com/ (build on top of Adobe React Aria)

## Validation
- Zod

## Forms state management 
Used for validation, blurring, interactions, are not part of Design Systems
- React Hook From (with Zod)

## Router
- React Router

## Animations
- React Spring
- Ant Motion if going with Ant Desing
