### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by tjementum** [platformplatform/PlatformPlatform#49]
```[tasklist]
### Tasks
- [x] #451
- [x] #391
- [x] #390
- [x] Add support for Gravatar
- [ ] #392
- [ ] #485
- [ ] #548
- [ ] https://github.com/platformplatform/PlatformPlatform/issues/552
- [ ] https://github.com/platformplatform/PlatformPlatform/issues/588
```
