### ISSUE TITLE
Cloud infrastructure

### ISSUE THREAD

**Issue by tjementum** [PlatformPlatform/platformplatform#60]
```[tasklist]
### Tasks
- [ ] https://github.com/PlatformPlatform/platformplatform/issues/61
- [ ] https://github.com/PlatformPlatform/platformplatform/issues/62
- [ ] https://github.com/PlatformPlatform/platformplatform/issues/126
- [ ] https://github.com/PlatformPlatform/platformplatform/issues/63
- [ ] https://github.com/PlatformPlatform/platformplatform/issues/64
- [ ] https://github.com/PlatformPlatform/platformplatform/issues/65
- [ ] https://github.com/PlatformPlatform/platformplatform/issues/66
- [ ] https://github.com/PlatformPlatform/platformplatform/issues/67
- [ ] https://github.com/PlatformPlatform/platformplatform/issues/68
- [ ] https://github.com/PlatformPlatform/platformplatform/issues/69
- [ ] https://github.com/PlatformPlatform/platformplatform/issues/70
- [ ] https://github.com/PlatformPlatform/platformplatform/issues/76
- [ ] https://github.com/PlatformPlatform/platformplatform/issues/155
- [ ] https://github.com/PlatformPlatform/platformplatform/issues/162
- [ ] https://github.com/PlatformPlatform/platformplatform/issues/163
- [ ] https://github.com/PlatformPlatform/platformplatform/issues/164
- [ ] https://github.com/PlatformPlatform/platformplatform/issues/161
- [ ] https://github.com/PlatformPlatform/platformplatform/issues/169
- [ ] https://github.com/PlatformPlatform/platformplatform/issues/170
- [ ] https://github.com/PlatformPlatform/platformplatform/issues/186
- [ ] https://github.com/PlatformPlatform/platformplatform/issues/187
```
